# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

permissions:
   issues: none

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
       # this job can now commit to the source code
       contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Lint the code
      run: echo "Linting the code"
